input_sources:
    d455_1:
        type: pointcloud2
        topic: /d455_1/depth/color/points
        queue_size: 5
        publish_on_update: true
    d455_2:
        type: pointcloud2
        topic: /d455_2/depth/color/points
        queue_size: 5
        publish_on_update: true
    l515_1:
        type: pointcloud2
        topic: /l515_1/depth/color/points
        queue_size: 5
        publish_on_update: true
    l515_2:
        type: pointcloud2
        topic: /l5152/depth/color/points
        queue_size: 5
        publish_on_update: true
map_frame_id: "map"
robot_base_frame_id: "david"
robot_pose_with_covariance: ""
