input_sources:
    d455_2:
        type: pointcloud
        topic: /d455_2/depth/color/points
        queue_size: 5
        publish_on_update: true
        sensor_processor:
            type: perfect

map_frame_id: "map"
robot_base_frame_id: "base_link"

robot_pose_with_covariance_topic: "/pose_with_covariance"
track_point_frame_id:                       "base_link"
track_point_x:                              0.0
track_point_y:                              0.0
track_point_z:                              0.0

# Map.
length_in_x:                                5.0
length_in_y:                                5.0
position_x:                                 0.0
position_y:                                 0.0
resolution:                                 0.1

