input_sources:
  d455_2:
    type: pointcloud
    topic: /d455_2/depth/color/points
    queue_size: 5
    publish_on_update: true
    sensor_processor:
      type: structured_light
      ignore_points_above: 1
      ignore_points_below: -2

map_frame_id: "map"
robot_base_frame_id: "t265_pose_frame"

robot_pose_with_covariance_topic: "/pose_with_covariance"
track_point_frame_id:                       "t265_pose_frame"
track_point_x:                              0.0
track_point_y:                              0.0
track_point_z:                              0.0

# Map.
length_in_x:                                15.0
length_in_y:                                15.0
position_x:                                 0.0
position_y:                                 0.0
resolution:                                 0.01

grid_map_topic: "elevation_mapping/elevation_map"
grid_map_visualization:
  # Setup occupancy grid
  - name: traversability_grid
    type: occupancy_grid
    params:
     layer: traversability
     data_min: -0.15
     data_max: 0.15