# Compose file for running the control computer.

services:
  ros:
    hostname: ros
    build: ../ros
    command: roscore
    environment:
      ROS_MASTER_URI: "http://david:11311"
    volumes:
      - ../ros:/lunabotics/ros
