# Configuration for the cost map. See
# https://wiki.ros.org/navigation/Tutorials/RobotSetup.

# Include objects that are 2.5 meters away in the local cost map.
static_map: false
obstacle_range: 2.5
transform_tolerance: 30
# Raytrace free space to 3 meters. TODO: what does this mean?
raytrace_range: 3.0

# Convex hull of the robot, in meters.
# TODO: Can we get this from the URDF?

footprint: [
  [-0.4, -0.4],
  [0.4, -0.4],
  [0.4, 0.4],
  [-0.4, 0.4]
]

subscribe_to_updates: true

map_topic: "/map"
inflation_radius: 0.4

# From https://answers.ros.org/question/293696/move_base-to-use-map-published-on-a-certain-topic/
plugins:
  - {name: inflation, type:"costmap_2d::InflationLayer"}
  - {name: obstacle_layer, type:"costmap_2d::ObstactleLayer"}
