# Global navigation cost-map configuration parameters.

global_costmap:
  # Not sure about /map here...
  global_frame: map 
  robot_base_frame: base_link
  update_frequency: 5
  rolling_window: true
  always_send_full_costmap: true
  map_type: costmap
  resolution: 0.05
  obstacle_range: 10
  # Use `static_map` because the map here is maintained by a map
  # server node.
  # Don't want a static map for SLAM. 
  static_map: false
